# Generated by Django 5.2.5 on 2025-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_liveclass_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
